### PR TITLE
fix: speech feature now works on all devices

### LINKED ISSUE #34: BUG: Speech not working on iOS
Speech did not work on iOS devices

### PR DESCRIPTION
**Pull request by sebuzz**
## Motivation

speech did not work on iOS devices

## Issues closed

closes #34

### CODE REVIEW

File: src/molecules/FrontSide/index.jsx [hunk 1]
```diff
@@ -15,10 +15,13 @@ const FrontSide = () => {
 	const learnMode = useStore(state => state.learnMode);
 
 	const speakIt = textToSpeak => {
-		let voices = speechSynthesis.getVoices();
-		let utterance = new SpeechSynthesisUtterance(textToSpeak);
-		utterance.voice = voices[58]; // 18 58
-		utterance.lang = "ja-JP";
+		const voices = speechSynthesis.getVoices();
+		const utterance = new SpeechSynthesisUtterance(textToSpeak);
+		//utterance.voice = voices[21]; // 18 58 // 21 // 58 works best for macOS Chrome, 21 for iOS
```
Comment (doemser) [inline src/molecules/FrontSide/index.jsx:20]: you need this?

**Review by doemser — APPROVED** [review]

File: src/molecules/FrontSide/index.jsx (hunk 1 above)
Comment (sebuzz) [reply src/molecules/FrontSide/index.jsx:20]: yes, as a reminder. ;)
